import 'package:flutter/material.dart';

/// This prints out every color generated by the seed
/// you provided in main.dart material theme.
/// To use this just put he code below in any page you want.
///               Expanded(
///                 child: Container(
///                   margin: const EdgeInsets.all(16),
///                   decoration: BoxDecoration(
///                     color: Colors.white.withAlpha(255),
///                     borderRadius: BorderRadius.circular(16),
///                     boxShadow: [
///                       BoxShadow(
///                         color: Colors.black26,
///                         blurRadius: 10,
///                         offset: Offset(0, 4),
///                       ),
///                     ],
///                   ),
///                   child: const ColorPaletteDebug(),
///                 ),
///               ),

class ColorsPage extends StatefulWidget {
  const ColorsPage({super.key});

  @override
  State<ColorsPage> createState() => _ColorsPageState();
}

class _ColorsPageState extends State<ColorsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(appBar: AppBar(), body: const ColorPaletteDebug());
  }
}

class ColorPaletteDebug extends StatelessWidget {
  const ColorPaletteDebug({super.key});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        _row('primary', cs.primary),
        _row('onPrimary', cs.onPrimary),
        _row('primaryContainer', cs.primaryContainer),
        _row('onPrimaryContainer', cs.onPrimaryContainer),

        _row('secondary', cs.secondary),
        _row('onSecondary', cs.onSecondary),
        _row('secondaryContainer', cs.secondaryContainer),
        _row('onSecondaryContainer', cs.onSecondaryContainer),

        _row('tertiary', cs.tertiary),
        _row('onTertiary', cs.onTertiary),
        _row('tertiaryContainer', cs.tertiaryContainer),
        _row('onTertiaryContainer', cs.onTertiaryContainer),

        _row('error', cs.error),
        _row('onError', cs.onError),
        _row('errorContainer', cs.errorContainer),
        _row('onErrorContainer', cs.onErrorContainer),

        _row('background', cs.surface),
        _row('onBackground', cs.onSurface),

        _row('surface', cs.surface),
        _row('onSurface', cs.onSurface),

        _row('surfaceDim', cs.surfaceDim),
        _row('surfaceBright', cs.surfaceBright),

        _row('surfaceContainerLowest', cs.surfaceContainerLowest),
        _row('surfaceContainerLow', cs.surfaceContainerLow),
        _row('surfaceContainer', cs.surfaceContainer),
        _row('surfaceContainerHigh', cs.surfaceContainerHigh),
        _row('surfaceContainerHighest', cs.surfaceContainerHighest),

        _row('surfaceVariant', cs.surfaceContainerHighest),
        _row('onSurfaceVariant', cs.onSurfaceVariant),

        _row('inverseSurface', cs.inverseSurface),
        _row('onInverseSurface', cs.onInverseSurface),
        _row('inversePrimary', cs.inversePrimary),

        _row('shadow', cs.shadow),
        _row('scrim', cs.scrim),

        _row('outline', cs.outline),
        _row('outlineVariant', cs.outlineVariant),
      ],
    );
  }

  Widget _row(String name, Color color) => ListTile(
    leading: CircleAvatar(backgroundColor: color),
    title: Text(name),
    trailing: SelectableText(
      '#${color.toARGB32().toRadixString(16).substring(2).toUpperCase()}',
      style: const TextStyle(fontFamily: 'monospace'),
    ),
  );
}
