// Mocks generated by Mockito 5.4.6 from annotations
// in inn/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i17;

import 'package:drift/drift.dart' as _i10;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i12;
import 'package:flutter/foundation.dart' as _i21;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i9;
import 'package:inn/core/database/app_database.dart' as _i11;
import 'package:inn/data/datasources/remote/auth_api.dart' as _i14;
import 'package:inn/data/datasources/remote/houses_api.dart' as _i18;
import 'package:inn/data/models/auth_models/login_request.dart' as _i16;
import 'package:inn/data/models/auth_models/login_response.dart' as _i3;
import 'package:inn/data/models/auth_models/sign_up_request.dart' as _i15;
import 'package:inn/data/models/auth_models/signup_response.dart' as _i2;
import 'package:inn/data/models/create_house_request.dart' as _i19;
import 'package:inn/data/models/extra_image_model.dart' as _i20;
import 'package:inn/data/models/favorite_model.dart' as _i7;
import 'package:inn/data/models/house_model.dart' as _i6;
import 'package:inn/data/models/paginated_response.dart' as _i5;
import 'package:inn/data/models/rating_model.dart' as _i8;
import 'package:inn/data/models/user_profile_model.dart' as _i4;
import 'package:inn/domain/repositories/auth_repository.dart' as _i23;
import 'package:inn/domain/repositories/favorites_repository.dart' as _i27;
import 'package:inn/domain/repositories/house_repository.dart' as _i24;
import 'package:inn/domain/repositories/location_repository.dart' as _i25;
import 'package:inn/domain/repositories/ratings_repository.dart' as _i26;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupResponse_0 extends _i1.SmartFake
    implements _i2.SignupResponse {
  _FakeSignupResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileModel_2 extends _i1.SmartFake
    implements _i4.UserProfileModel {
  _FakeUserProfileModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponse_3<T> extends _i1.SmartFake
    implements _i5.PaginatedResponse<T> {
  _FakePaginatedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHouseModel_4 extends _i1.SmartFake implements _i6.HouseModel {
  _FakeHouseModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageDetail_5 extends _i1.SmartFake implements _i6.ImageDetail {
  _FakeImageDetail_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoriteModel_6 extends _i1.SmartFake implements _i7.FavoriteModel {
  _FakeFavoriteModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRatingModel_7 extends _i1.SmartFake implements _i8.RatingModel {
  _FakeRatingModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_8 extends _i1.SmartFake implements _i9.IOSOptions {
  _FakeIOSOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_9 extends _i1.SmartFake
    implements _i9.AndroidOptions {
  _FakeAndroidOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_10 extends _i1.SmartFake implements _i9.LinuxOptions {
  _FakeLinuxOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_11 extends _i1.SmartFake
    implements _i9.WindowsOptions {
  _FakeWindowsOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_12 extends _i1.SmartFake implements _i9.WebOptions {
  _FakeWebOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_13 extends _i1.SmartFake implements _i9.MacOsOptions {
  _FakeMacOsOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_14 extends _i1.SmartFake
    implements _i10.MigrationStrategy {
  _FakeMigrationStrategy_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_15 extends _i1.SmartFake
    implements _i11.$AppDatabaseManager {
  _Fake$AppDatabaseManager_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HousesTableTable_16 extends _i1.SmartFake
    implements _i11.$HousesTableTable {
  _Fake$HousesTableTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MyHousesTableTable_17 extends _i1.SmartFake
    implements _i11.$MyHousesTableTable {
  _Fake$MyHousesTableTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$FavoritesTableTable_18 extends _i1.SmartFake
    implements _i11.$FavoritesTableTable {
  _Fake$FavoritesTableTable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserProfileTableTable_19 extends _i1.SmartFake
    implements _i11.$UserProfileTableTable {
  _Fake$UserProfileTableTable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_20 extends _i1.SmartFake
    implements _i10.GeneratedDatabase {
  _FakeGeneratedDatabase_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_21 extends _i1.SmartFake
    implements _i10.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_22 extends _i1.SmartFake
    implements _i10.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_23 extends _i1.SmartFake
    implements _i10.DatabaseConnection {
  _FakeDatabaseConnection_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_24 extends _i1.SmartFake
    implements _i10.QueryExecutor {
  _FakeQueryExecutor_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_25 extends _i1.SmartFake
    implements _i12.StreamQueryStore {
  _FakeStreamQueryStore_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_26 extends _i1.SmartFake
    implements _i10.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_27 extends _i1.SmartFake implements _i10.Migrator {
  _FakeMigrator_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_28<T> extends _i1.SmartFake implements _i13.Future<T> {
  _FakeFuture_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_29<T1 extends _i10.Table, D1> extends _i1.SmartFake
    implements _i10.InsertStatement<T1, D1> {
  _FakeInsertStatement_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_30<T extends _i10.Table, D> extends _i1.SmartFake
    implements _i10.UpdateStatement<T, D> {
  _FakeUpdateStatement_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_31<T1 extends _i10.HasResultSet, D>
    extends _i1.SmartFake
    implements _i10.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_32<FirstT extends _i10.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i10.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_33<Row> extends _i1.SmartFake
    implements _i10.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_34<T1 extends _i10.Table, D1> extends _i1.SmartFake
    implements _i10.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_35<T> extends _i1.SmartFake
    implements _i10.Selectable<T> {
  _FakeSelectable_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_36 extends _i1.SmartFake
    implements _i10.GenerationContext {
  _FakeGenerationContext_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i14.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.SignupResponse> signUp(_i15.SignUpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i13.Future<_i2.SignupResponse>.value(
              _FakeSignupResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i13.Future<_i2.SignupResponse>);

  @override
  _i13.Future<_i3.LoginResponse> login(_i16.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i13.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i13.Future<_i3.LoginResponse>);

  @override
  _i13.Future<_i4.UserProfileModel> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i13.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i13.Future<_i4.UserProfileModel>);

  @override
  _i13.Future<_i4.UserProfileModel> createUserProfile({
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? dob,
    String? gender,
    String? address,
    String? bio,
    int? country,
    int? state,
    int? city,
    int? neighborhood,
    _i17.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phoneNumber: phoneNumber,
              #dob: dob,
              #gender: gender,
              #address: address,
              #bio: bio,
              #country: country,
              #state: state,
              #city: city,
              #neighborhood: neighborhood,
              #profilePicture: profilePicture,
            }),
            returnValue: _i13.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#createUserProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #phoneNumber: phoneNumber,
                  #dob: dob,
                  #gender: gender,
                  #address: address,
                  #bio: bio,
                  #country: country,
                  #state: state,
                  #city: city,
                  #neighborhood: neighborhood,
                  #profilePicture: profilePicture,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserProfileModel>);

  @override
  _i13.Future<_i4.UserProfileModel> updateUserProfile({
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? dob,
    String? gender,
    String? address,
    String? bio,
    int? country,
    int? state,
    int? city,
    int? neighborhood,
    _i17.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phoneNumber: phoneNumber,
              #dob: dob,
              #gender: gender,
              #address: address,
              #bio: bio,
              #country: country,
              #state: state,
              #city: city,
              #neighborhood: neighborhood,
              #profilePicture: profilePicture,
            }),
            returnValue: _i13.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #phoneNumber: phoneNumber,
                  #dob: dob,
                  #gender: gender,
                  #address: address,
                  #bio: bio,
                  #country: country,
                  #state: state,
                  #city: city,
                  #neighborhood: neighborhood,
                  #profilePicture: profilePicture,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserProfileModel>);
}

/// A class which mocks [HousesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockHousesApi extends _i1.Mock implements _i18.HousesApi {
  MockHousesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>> fetchHouses({
    int? page = 1,
    String? search,
    num? minPrice,
    num? maxPrice,
    String? city,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHouses, [], {
              #page: page,
              #search: search,
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #city: city,
              #category: category,
            }),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>.value(
                  _FakePaginatedResponse_3<_i6.HouseModel>(
                    this,
                    Invocation.method(#fetchHouses, [], {
                      #page: page,
                      #search: search,
                      #minPrice: minPrice,
                      #maxPrice: maxPrice,
                      #city: city,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>);

  @override
  _i13.Future<_i6.HouseModel> getHouse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getHouse, [id]),
            returnValue: _i13.Future<_i6.HouseModel>.value(
              _FakeHouseModel_4(this, Invocation.method(#getHouse, [id])),
            ),
          )
          as _i13.Future<_i6.HouseModel>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>> getMyHouses() =>
      (super.noSuchMethod(
            Invocation.method(#getMyHouses, []),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>.value(
                  _FakePaginatedResponse_3<_i6.HouseModel>(
                    this,
                    Invocation.method(#getMyHouses, []),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>);

  @override
  _i13.Future<_i6.HouseModel> createHouse(_i19.CreateHouseRequest? house) =>
      (super.noSuchMethod(
            Invocation.method(#createHouse, [house]),
            returnValue: _i13.Future<_i6.HouseModel>.value(
              _FakeHouseModel_4(this, Invocation.method(#createHouse, [house])),
            ),
          )
          as _i13.Future<_i6.HouseModel>);

  @override
  _i13.Future<_i6.HouseModel> updateHouse(
    int? id,
    _i19.CreateHouseRequest? house,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHouse, [id, house]),
            returnValue: _i13.Future<_i6.HouseModel>.value(
              _FakeHouseModel_4(
                this,
                Invocation.method(#updateHouse, [id, house]),
              ),
            ),
          )
          as _i13.Future<_i6.HouseModel>);

  @override
  _i13.Future<void> deleteHouse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHouse, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.Country>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i13.Future<_i5.PaginatedResponse<_i6.Country>>.value(
              _FakePaginatedResponse_3<_i6.Country>(
                this,
                Invocation.method(#getCountries, []),
              ),
            ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.Country>>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.StateData>> getStates(int? countryId) =>
      (super.noSuchMethod(
            Invocation.method(#getStates, [countryId]),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.StateData>>.value(
                  _FakePaginatedResponse_3<_i6.StateData>(
                    this,
                    Invocation.method(#getStates, [countryId]),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.StateData>>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.City>> getCities(int? stateId) =>
      (super.noSuchMethod(
            Invocation.method(#getCities, [stateId]),
            returnValue: _i13.Future<_i5.PaginatedResponse<_i6.City>>.value(
              _FakePaginatedResponse_3<_i6.City>(
                this,
                Invocation.method(#getCities, [stateId]),
              ),
            ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.City>>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.Neighborhood>> getNeighborhoods(
    int? cityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNeighborhoods, [cityId]),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.Neighborhood>>.value(
                  _FakePaginatedResponse_3<_i6.Neighborhood>(
                    this,
                    Invocation.method(#getNeighborhoods, [cityId]),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.Neighborhood>>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.ImageDetail>> getImages() =>
      (super.noSuchMethod(
            Invocation.method(#getImages, []),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.ImageDetail>>.value(
                  _FakePaginatedResponse_3<_i6.ImageDetail>(
                    this,
                    Invocation.method(#getImages, []),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.ImageDetail>>);

  @override
  _i13.Future<_i6.ImageDetail> uploadImage(_i17.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [image]),
            returnValue: _i13.Future<_i6.ImageDetail>.value(
              _FakeImageDetail_5(
                this,
                Invocation.method(#uploadImage, [image]),
              ),
            ),
          )
          as _i13.Future<_i6.ImageDetail>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i7.FavoriteModel>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i7.FavoriteModel>>.value(
                  _FakePaginatedResponse_3<_i7.FavoriteModel>(
                    this,
                    Invocation.method(#getFavorites, []),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i7.FavoriteModel>>);

  @override
  _i13.Future<_i7.FavoriteModel> addFavorite(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [body]),
            returnValue: _i13.Future<_i7.FavoriteModel>.value(
              _FakeFavoriteModel_6(
                this,
                Invocation.method(#addFavorite, [body]),
              ),
            ),
          )
          as _i13.Future<_i7.FavoriteModel>);

  @override
  _i13.Future<void> deleteFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i8.RatingModel>> getRatings() =>
      (super.noSuchMethod(
            Invocation.method(#getRatings, []),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i8.RatingModel>>.value(
                  _FakePaginatedResponse_3<_i8.RatingModel>(
                    this,
                    Invocation.method(#getRatings, []),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i8.RatingModel>>);

  @override
  _i13.Future<_i8.RatingModel> addRating(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#addRating, [body]),
            returnValue: _i13.Future<_i8.RatingModel>.value(
              _FakeRatingModel_7(this, Invocation.method(#addRating, [body])),
            ),
          )
          as _i13.Future<_i8.RatingModel>);

  @override
  _i13.Future<_i8.RatingModel> updateRating(
    int? id,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [id, body]),
            returnValue: _i13.Future<_i8.RatingModel>.value(
              _FakeRatingModel_7(
                this,
                Invocation.method(#updateRating, [id, body]),
              ),
            ),
          )
          as _i13.Future<_i8.RatingModel>);

  @override
  _i13.Future<void> deleteRating(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRating, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i20.ExtraImageModel>> getExtraImages({
    int? rentalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExtraImages, [], {#rentalId: rentalId}),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i20.ExtraImageModel>>.value(
                  _FakePaginatedResponse_3<_i20.ExtraImageModel>(
                    this,
                    Invocation.method(#getExtraImages, [], {
                      #rentalId: rentalId,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i20.ExtraImageModel>>);

  @override
  _i13.Future<List<_i20.ExtraImageModel>> uploadExtraImages({
    required int? rental,
    required List<_i17.File>? images,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadExtraImages, [], {
              #rental: rental,
              #images: images,
            }),
            returnValue: _i13.Future<List<_i20.ExtraImageModel>>.value(
              <_i20.ExtraImageModel>[],
            ),
          )
          as _i13.Future<List<_i20.ExtraImageModel>>);

  @override
  _i13.Future<void> deleteExtraImage(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExtraImage, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i9.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_8(this, Invocation.getter(#iOptions)),
          )
          as _i9.IOSOptions);

  @override
  _i9.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_9(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i9.AndroidOptions);

  @override
  _i9.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_10(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i9.LinuxOptions);

  @override
  _i9.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_11(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i9.WindowsOptions);

  @override
  _i9.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_12(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i9.WebOptions);

  @override
  _i9.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_13(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i9.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i21.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i21.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> write({
    required String? key,
    required String? value,
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String?> read({
    required String? key,
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<bool> containsKey({
    required String? key,
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> delete({
    required String? key,
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Map<String, String>> readAll({
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i13.Future<Map<String, String>>);

  @override
  _i13.Future<void> deleteAll({
    _i9.IOSOptions? iOptions,
    _i9.AndroidOptions? aOptions,
    _i9.LinuxOptions? lOptions,
    _i9.WebOptions? webOptions,
    _i9.MacOsOptions? mOptions,
    _i9.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i13.Future<bool?>.value(),
          )
          as _i13.Future<bool?>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i11.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i10.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_14(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i10.MigrationStrategy);

  @override
  _i11.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_15(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i11.$AppDatabaseManager);

  @override
  _i11.$HousesTableTable get housesTable =>
      (super.noSuchMethod(
            Invocation.getter(#housesTable),
            returnValue: _Fake$HousesTableTable_16(
              this,
              Invocation.getter(#housesTable),
            ),
          )
          as _i11.$HousesTableTable);

  @override
  _i11.$MyHousesTableTable get myHousesTable =>
      (super.noSuchMethod(
            Invocation.getter(#myHousesTable),
            returnValue: _Fake$MyHousesTableTable_17(
              this,
              Invocation.getter(#myHousesTable),
            ),
          )
          as _i11.$MyHousesTableTable);

  @override
  _i11.$FavoritesTableTable get favoritesTable =>
      (super.noSuchMethod(
            Invocation.getter(#favoritesTable),
            returnValue: _Fake$FavoritesTableTable_18(
              this,
              Invocation.getter(#favoritesTable),
            ),
          )
          as _i11.$FavoritesTableTable);

  @override
  _i11.$UserProfileTableTable get userProfileTable =>
      (super.noSuchMethod(
            Invocation.getter(#userProfileTable),
            returnValue: _Fake$UserProfileTableTable_19(
              this,
              Invocation.getter(#userProfileTable),
            ),
          )
          as _i11.$UserProfileTableTable);

  @override
  Iterable<_i10.TableInfo<_i10.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i10.TableInfo<_i10.Table, Object?>>[],
          )
          as Iterable<_i10.TableInfo<_i10.Table, Object?>>);

  @override
  List<_i10.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i10.DatabaseSchemaEntity>[],
          )
          as List<_i10.DatabaseSchemaEntity>);

  @override
  _i10.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_20(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i10.GeneratedDatabase);

  @override
  _i10.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_21(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i10.DriftDatabaseOptions);

  @override
  _i10.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_22(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i10.StreamQueryUpdateRules);

  @override
  _i10.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_23(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i10.DatabaseConnection);

  @override
  _i10.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i22.dummyValue<_i10.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i10.SqlTypes);

  @override
  _i10.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_24(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i10.QueryExecutor);

  @override
  _i12.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_25(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i12.StreamQueryStore);

  @override
  _i10.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_26(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i10.DatabaseConnectionUser);

  @override
  _i13.Future<void> insertHouses(List<_i6.HouseModel>? houses) =>
      (super.noSuchMethod(
            Invocation.method(#insertHouses, [houses]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Stream<List<_i6.HouseModel>> watchHouses() =>
      (super.noSuchMethod(
            Invocation.method(#watchHouses, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Future<void> clearHouses() =>
      (super.noSuchMethod(
            Invocation.method(#clearHouses, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<int> getHouseCount() =>
      (super.noSuchMethod(
            Invocation.method(#getHouseCount, []),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<DateTime?> getLatestFetchTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestFetchTime, []),
            returnValue: _i13.Future<DateTime?>.value(),
          )
          as _i13.Future<DateTime?>);

  @override
  _i13.Future<void> insertMyHouses(List<_i6.HouseModel>? houses) =>
      (super.noSuchMethod(
            Invocation.method(#insertMyHouses, [houses]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Stream<List<_i6.HouseModel>> watchMyHouses() =>
      (super.noSuchMethod(
            Invocation.method(#watchMyHouses, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Future<int> getMyHousesCount() =>
      (super.noSuchMethod(
            Invocation.method(#getMyHousesCount, []),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<DateTime?> getLatestMyHouseFetchTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestMyHouseFetchTime, []),
            returnValue: _i13.Future<DateTime?>.value(),
          )
          as _i13.Future<DateTime?>);

  @override
  _i13.Future<void> deleteMyHouse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMyHouse, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> insertFavorite({
    required _i6.HouseModel? house,
    int? apiId,
    bool? isSynced = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertFavorite, [], {
              #house: house,
              #apiId: apiId,
              #isSynced: isSynced,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteFavorite(int? houseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [houseId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteFavoriteByApiId(int? apiId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavoriteByApiId, [apiId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Stream<List<_i6.HouseModel>> watchFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#watchFavorites, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Future<int?> getFavoriteApiId(int? houseId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteApiId, [houseId]),
            returnValue: _i13.Future<int?>.value(),
          )
          as _i13.Future<int?>);

  @override
  _i13.Stream<List<int>> watchFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#watchFavoriteIds, []),
            returnValue: _i13.Stream<List<int>>.empty(),
          )
          as _i13.Stream<List<int>>);

  @override
  _i13.Future<bool> isHouseFavorite(int? houseId) =>
      (super.noSuchMethod(
            Invocation.method(#isHouseFavorite, [houseId]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> insertUserProfile(_i4.UserProfileModel? profile) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserProfile, [profile]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.UserProfileModel?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i13.Future<_i4.UserProfileModel?>.value(),
          )
          as _i13.Future<_i4.UserProfileModel?>);

  @override
  _i13.Future<void> clearUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserProfile, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i10.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_27(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i10.Migrator);

  @override
  _i13.Future<void> beforeOpen(
    _i10.QueryExecutor? executor,
    _i10.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Ret> computeWithDatabase<Ret, DB extends _i10.GeneratedDatabase>({
    required _i13.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i10.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i13.Future<Ret>.value(v),
                ) ??
                _FakeFuture_28<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i13.Future<Ret>);

  @override
  _i13.Stream<T> createStream<T extends Object>(
    _i12.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i13.Stream<T>.empty(),
          )
          as _i13.Stream<T>);

  @override
  T alias<T, D>(_i10.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i22.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(
    Iterable<_i10.TableInfo<_i10.Table, dynamic>>? tables,
  ) => super.noSuchMethod(
    Invocation.method(#markTablesUpdated, [tables]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyUpdates(Set<_i10.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Stream<Set<_i10.TableUpdate>> tableUpdates([
    _i10.TableUpdateQuery? query = const _i10.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i13.Stream<Set<_i10.TableUpdate>>.empty(),
          )
          as _i13.Stream<Set<_i10.TableUpdate>>);

  @override
  _i13.Future<T> doWhenOpened<T>(
    _i13.FutureOr<T> Function(_i10.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i13.Future<T>);

  @override
  _i10.InsertStatement<T, D> into<T extends _i10.Table, D>(
    _i10.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_29<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i10.InsertStatement<T, D>);

  @override
  _i10.UpdateStatement<Tbl, R> update<Tbl extends _i10.Table, R>(
    _i10.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_30<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i10.UpdateStatement<Tbl, R>);

  @override
  _i10.SimpleSelectStatement<T, R> select<T extends _i10.HasResultSet, R>(
    _i10.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_31<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i10.SimpleSelectStatement<T, R>);

  @override
  _i10.JoinedSelectStatement<T, R> selectOnly<T extends _i10.HasResultSet, R>(
    _i10.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_32<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i10.JoinedSelectStatement<T, R>);

  @override
  _i10.BaseSelectStatement<_i10.TypedResult> selectExpressions(
    Iterable<_i10.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_33<_i10.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i10.BaseSelectStatement<_i10.TypedResult>);

  @override
  _i10.DeleteStatement<T, D> delete<T extends _i10.Table, D>(
    _i10.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_34<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i10.DeleteStatement<T, D>);

  @override
  _i13.Future<int> customUpdate(
    String? query, {
    List<_i10.Variable<Object>>? variables = const [],
    Set<_i10.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i10.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<int> customInsert(
    String? query, {
    List<_i10.Variable<Object>>? variables = const [],
    Set<_i10.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<List<_i10.QueryRow>> customWriteReturning(
    String? query, {
    List<_i10.Variable<Object>>? variables = const [],
    Set<_i10.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i10.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<List<_i10.QueryRow>>.value(
              <_i10.QueryRow>[],
            ),
          )
          as _i13.Future<List<_i10.QueryRow>>);

  @override
  _i10.Selectable<_i10.QueryRow> customSelect(
    String? query, {
    List<_i10.Variable<Object>>? variables = const [],
    Set<_i10.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i10.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i10.Selectable<_i10.QueryRow>);

  @override
  _i10.Selectable<_i10.QueryRow> customSelectQuery(
    String? query, {
    List<_i10.Variable<Object>>? variables = const [],
    Set<_i10.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i10.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i10.Selectable<_i10.QueryRow>);

  @override
  _i13.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> transaction<T>(
    _i13.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<T> exclusively<T>(_i13.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<void> batch(
    _i13.FutureOr<void> Function(_i10.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> runWithInterceptor<T>(
    _i13.Future<T> Function()? action, {
    required _i10.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i10.GenerationContext $write(
    _i10.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i10.GenerationContext);

  @override
  _i10.GenerationContext $writeInsertable(
    _i10.TableInfo<_i10.Table, dynamic>? table,
    _i10.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i10.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i23.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.SignupResponse> signUp({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<_i2.SignupResponse>.value(
              _FakeSignupResponse_0(
                this,
                Invocation.method(#signUp, [], {
                  #username: username,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i2.SignupResponse>);

  @override
  _i13.Future<_i3.LoginResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i13.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i3.LoginResponse>);

  @override
  _i13.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.UserProfileModel?> getUserProfile({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i13.Future<_i4.UserProfileModel?>.value(),
          )
          as _i13.Future<_i4.UserProfileModel?>);

  @override
  _i13.Future<_i4.UserProfileModel> createUserProfile({
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? dob,
    String? gender,
    String? address,
    String? bio,
    int? country,
    int? state,
    int? city,
    int? neighborhood,
    _i17.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phoneNumber: phoneNumber,
              #dob: dob,
              #gender: gender,
              #address: address,
              #bio: bio,
              #country: country,
              #state: state,
              #city: city,
              #neighborhood: neighborhood,
              #profilePicture: profilePicture,
            }),
            returnValue: _i13.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#createUserProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #phoneNumber: phoneNumber,
                  #dob: dob,
                  #gender: gender,
                  #address: address,
                  #bio: bio,
                  #country: country,
                  #state: state,
                  #city: city,
                  #neighborhood: neighborhood,
                  #profilePicture: profilePicture,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserProfileModel>);

  @override
  _i13.Future<_i4.UserProfileModel> updateUserProfile({
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? dob,
    String? gender,
    String? address,
    String? bio,
    int? country,
    int? state,
    int? city,
    int? neighborhood,
    _i17.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phoneNumber: phoneNumber,
              #dob: dob,
              #gender: gender,
              #address: address,
              #bio: bio,
              #country: country,
              #state: state,
              #city: city,
              #neighborhood: neighborhood,
              #profilePicture: profilePicture,
            }),
            returnValue: _i13.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #phoneNumber: phoneNumber,
                  #dob: dob,
                  #gender: gender,
                  #address: address,
                  #bio: bio,
                  #country: country,
                  #state: state,
                  #city: city,
                  #neighborhood: neighborhood,
                  #profilePicture: profilePicture,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserProfileModel>);
}

/// A class which mocks [HouseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHouseRepository extends _i1.Mock implements _i24.HouseRepository {
  MockHouseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<List<_i6.HouseModel>> watchHouses() =>
      (super.noSuchMethod(
            Invocation.method(#watchHouses, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Future<void> fetchRecentHouses() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecentHouses, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> fetchHousesPage(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHousesPage, [page]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> shouldFetchHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#shouldFetchHomeData, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>> searchHouses(
    String? query, {
    int? page = 1,
    num? minPrice,
    num? maxPrice,
    String? city,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchHouses,
              [query],
              {
                #page: page,
                #minPrice: minPrice,
                #maxPrice: maxPrice,
                #city: city,
                #category: category,
              },
            ),
            returnValue:
                _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>.value(
                  _FakePaginatedResponse_3<_i6.HouseModel>(
                    this,
                    Invocation.method(
                      #searchHouses,
                      [query],
                      {
                        #page: page,
                        #minPrice: minPrice,
                        #maxPrice: maxPrice,
                        #city: city,
                        #category: category,
                      },
                    ),
                  ),
                ),
          )
          as _i13.Future<_i5.PaginatedResponse<_i6.HouseModel>>);

  @override
  _i13.Stream<List<_i6.HouseModel>> watchMyProperties() =>
      (super.noSuchMethod(
            Invocation.method(#watchMyProperties, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Future<void> fetchMyProperties({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyProperties, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i6.HouseModel> createHouse(_i19.CreateHouseRequest? house) =>
      (super.noSuchMethod(
            Invocation.method(#createHouse, [house]),
            returnValue: _i13.Future<_i6.HouseModel>.value(
              _FakeHouseModel_4(this, Invocation.method(#createHouse, [house])),
            ),
          )
          as _i13.Future<_i6.HouseModel>);

  @override
  _i13.Future<_i6.HouseModel> updateHouse(
    int? id,
    _i19.CreateHouseRequest? house,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHouse, [id, house]),
            returnValue: _i13.Future<_i6.HouseModel>.value(
              _FakeHouseModel_4(
                this,
                Invocation.method(#updateHouse, [id, house]),
              ),
            ),
          )
          as _i13.Future<_i6.HouseModel>);

  @override
  _i13.Future<void> deleteRating(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRating, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i20.ExtraImageModel>> getExtraImages({int? rentalId}) =>
      (super.noSuchMethod(
            Invocation.method(#getExtraImages, [], {#rentalId: rentalId}),
            returnValue: _i13.Future<List<_i20.ExtraImageModel>>.value(
              <_i20.ExtraImageModel>[],
            ),
          )
          as _i13.Future<List<_i20.ExtraImageModel>>);

  @override
  _i13.Future<List<_i20.ExtraImageModel>> uploadExtraImages(
    int? rentalId,
    List<_i17.File>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadExtraImages, [rentalId, images]),
            returnValue: _i13.Future<List<_i20.ExtraImageModel>>.value(
              <_i20.ExtraImageModel>[],
            ),
          )
          as _i13.Future<List<_i20.ExtraImageModel>>);

  @override
  _i13.Future<void> deleteExtraImage(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExtraImage, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteHouse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHouse, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i25.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i6.Country>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i13.Future<List<_i6.Country>>.value(<_i6.Country>[]),
          )
          as _i13.Future<List<_i6.Country>>);

  @override
  _i13.Future<List<_i6.StateData>> getStates(int? countryId) =>
      (super.noSuchMethod(
            Invocation.method(#getStates, [countryId]),
            returnValue: _i13.Future<List<_i6.StateData>>.value(
              <_i6.StateData>[],
            ),
          )
          as _i13.Future<List<_i6.StateData>>);

  @override
  _i13.Future<List<_i6.City>> getCities(int? stateId) =>
      (super.noSuchMethod(
            Invocation.method(#getCities, [stateId]),
            returnValue: _i13.Future<List<_i6.City>>.value(<_i6.City>[]),
          )
          as _i13.Future<List<_i6.City>>);

  @override
  _i13.Future<List<_i6.Neighborhood>> getNeighborhoods(int? cityId) =>
      (super.noSuchMethod(
            Invocation.method(#getNeighborhoods, [cityId]),
            returnValue: _i13.Future<List<_i6.Neighborhood>>.value(
              <_i6.Neighborhood>[],
            ),
          )
          as _i13.Future<List<_i6.Neighborhood>>);
}

/// A class which mocks [RatingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingsRepository extends _i1.Mock implements _i26.RatingsRepository {
  MockRatingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i8.RatingModel>> getUserRatings() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRatings, []),
            returnValue: _i13.Future<List<_i8.RatingModel>>.value(
              <_i8.RatingModel>[],
            ),
          )
          as _i13.Future<List<_i8.RatingModel>>);

  @override
  _i13.Future<_i8.RatingModel> addRating({
    required int? houseId,
    required int? stars,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRating, [], {
              #houseId: houseId,
              #stars: stars,
              #reason: reason,
            }),
            returnValue: _i13.Future<_i8.RatingModel>.value(
              _FakeRatingModel_7(
                this,
                Invocation.method(#addRating, [], {
                  #houseId: houseId,
                  #stars: stars,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.RatingModel>);

  @override
  _i13.Future<_i8.RatingModel> updateRating({
    required int? ratingId,
    required int? houseId,
    required int? stars,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [], {
              #ratingId: ratingId,
              #houseId: houseId,
              #stars: stars,
              #reason: reason,
            }),
            returnValue: _i13.Future<_i8.RatingModel>.value(
              _FakeRatingModel_7(
                this,
                Invocation.method(#updateRating, [], {
                  #ratingId: ratingId,
                  #houseId: houseId,
                  #stars: stars,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.RatingModel>);

  @override
  _i13.Future<void> deleteRating(int? ratingId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRating, [ratingId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i27.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<List<_i6.HouseModel>> watchFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#watchFavorites, []),
            returnValue: _i13.Stream<List<_i6.HouseModel>>.empty(),
          )
          as _i13.Stream<List<_i6.HouseModel>>);

  @override
  _i13.Stream<List<int>> watchFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#watchFavoriteIds, []),
            returnValue: _i13.Stream<List<int>>.empty(),
          )
          as _i13.Stream<List<int>>);

  @override
  _i13.Future<void> syncFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#syncFavorites, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> toggleFavorite(_i6.HouseModel? house) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [house]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}
